version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'arosaje'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3307'
    volumes:
      - C:\Users\Benoit\docker-workspace\db-data:/var/lib/mysql
    networks:
      - mspr01_network

  db_manager:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 91:80
    environment:
      - PMA_HOST=database
    networks:
      - mspr01_network

  app:
    image: php-mspr01
    ports:
      - '8080:80'
    environment:
      DATABASE_URL: mysql://root:root@database:3307/arosaje
    networks:
      - mspr01_network

networks:
    mspr01_network:
